# Generated by Django 6.0.3 on 2026-03-06 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_sensordata_farm_crop_alert_irrigationrecommendation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='planted_at',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='variety',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='location',
        ),
        migrations.RemoveField(
            model_name='sensornode',
            name='installed_at',
        ),
        migrations.RemoveField(
            model_name='sensornode',
            name='location',
        ),
    ]
